### ISSUE TITLE
extra_hosts settings in config.toml ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppet-gitlab#121]
for some reason I've hit a docker issue with DNS lookups.. so I need to add:

extra_hosts = ["mygiturl:mygithostip"] - to config.toml - under runners.docker.

The module does not support this currently.. and does not handle if config.toml file is missing :(

Any plans for supporting setting such settings on runner setup ?

**Comment by tobru** [comment]
Yes, why not. Are you willing to create a PR?

**Comment by KlavsKlavsen** [comment]
currently you're using fileline to change that file.. whats the reason for not controlling the entire file?

**Comment by KlavsKlavsen** [comment]
and yes - I'll gladly do a PR.. if we agree on how best to solve it :)

**Comment by LongLiveCHIEF** [comment]
Functionality for gitlab runner is being moved into its own module at https://github.com/voxpupuli/puppet-gitlab_ci_runner
