### ISSUE TITLE
runner unregister

### ISSUE THREAD

**Issue by cova-fe** [voxpupuli/puppet-gitlab#123]
Hi,
I was wondering if there is a way to tell cirunner to unregister a runner, maybe adding a "ensure absent" parameter, or something like that.
Is something feasible/useful/planned?
If yes, I could have a look at it

**Comment by tobru** [comment]
This is probably not easily possible as there would have to be communication with the Gitlab API. This is not yet implemented and also not planned in the near future. If you want to work on this, I'll be happy to see a pull request.

**Comment by timhughes** [comment]
I use the folloowing in my profile to clean up old runners. It doesnt unregister but you can delete them from the UI and then the module will recreate them with the updated config. 

```
  exec { 'gitlab-delete-broken':
    command => 'gitlab-runner verify --delete',
    onlyif  => 'gitlab-runner verify 2>&1 | grep -q "is removed"',
    require => Class['::gitlab::cirunner'],
    returns => 0,
    path    => ['/bin', '/usr/bin', '/usr/sbin'],
  }
```

**Comment by SirUrban** [comment]
Have a look at: https://github.com/voxpupuli/puppet-gitlab/pull/178
