### ISSUE TITLE
Add a feature to make gitlab-runner member of docker group

### ISSUE THREAD

**Issue by gdubicki** [voxpupuli/puppet-gitlab#150]
Pleae make this module optionally do step 4. from https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-shell-executor in case you want to use the runner for building Docker images.

You can do it with a hacky-but-working:

```
exec {'add gitlab-runner to docker group':
    command => '/sbin/usermod -aG docker gitlab-runner',
    unless  => '/bin/grep -q "docker\\S*gitlab-runner" /etc/group',
}
```

**Comment by mjburling** [comment]
> You can do it with a hacky-but-working

I don't think it's all that bad. It's at least idempotent, right?

I've been on the look out for circumstances where a virtual resource would be an acceptable solution. Would this qualify:
```
@user {'gitlab-runner':
  groups  => ["docker"],
}
```

For now, I've just added it to my gitlabci-docker role's hiera:
```
docker::docker_users:
  - gitlab-runner
```

And I don't think the resource generated here is all that different from what you've suggested above:
```
# from /opt/puppetlabs/puppet/cache/state/resources.txt
[...]
exec[/usr/sbin/usermod -aG docker gitlab-runner]
[...]
```

**Comment by LongLiveCHIEF** [comment]
I'm going to migrate this issue to the new https://github.com/voxpupuli/puppet-gitlab-ci-runner project. The next major release of this module will remove all gitlab runner functionality into that new module.
