### ISSUE TITLE
Regression: yum $releasever results in 404 error for RHEL yum repo

### ISSUE THREAD

**Issue by esalberg** [voxpupuli/puppet-gitlab#153]
This commit, which changes ${releasever} (set to 5/6/7 for RHEL) to \$releasever (uses the yum releasever) does not work for us on RHEL6.  The yum $releasever is 6Server, and the actual gitlab URL needs just 6.
https://github.com/vshn/puppet-gitlab/commit/1192cc6a4c4b4e9dc30b4775c9dc3dc6f4ca0bbd

This was previously noted and fixed / working fine, e.g. as seen in this issue:
https://github.com/vshn/puppet-gitlab/issues/42

I'm happy to put in a PR (I forked the module anyway so that I could get my upgrade to proceed), but I wanted to put in an issue first to get confirmation.

**Comment by esalberg** [comment]
Also, since the old code used is_hash, and that is deprecated, would you prefer:
1) ignore $::os[release][major] and just use $::operatingsystemrelease
2) use validate_legacy (but that only supports Puppet 4.4.x+, so may be too version restricting)
3) replace it another way?

Code in question:
        if is_hash($::os) {
          $releasever = $::os[release][major]
        } else {
          $releasever = $::operatingsystemmajrelease
        }

**Comment by Poil** [comment]
+1

**Comment by jsmelser** [comment]
I am getting this on redhat 7 as well.

**Comment by TJuberg** [comment]
I can confirm that this issue is affecting us on Redhat Enterprise Linux as well

**Comment by mhyzon** [comment]
I created #172 which fixes this issue (again, I guess?) and also adds the proper GPG key for EE if you are using EE and enables RPM verification.

**Comment by pebtron** [comment]
I can also confirm that on RHEL7 the URL https://packages.gitlab.com/gitlab/gitlab-ce/el/7Server/x86_64/repodata/repomd.xml 404's. The correct URL should be https://packages.gitlab.com/gitlab/gitlab-ce/el/7/x86_64/repodata/repomd.xml.

**Comment by juniorsysadmin** [comment]
Fixed by #172 I think
