### ISSUE TITLE
Facter code still exists from Issue 131

### ISSUE THREAD

**Issue by mhyzon** [voxpupuli/puppet-gitlab#170]
I just commented in #131, but maybe it is better form to open up a new Issue rather than comment on a closed one?

Anyway, @LongLiveCHIEF's merge request removed references to the `::gitlab_systemd` fact from `init.pp`, `params.pp`, and `service.pp`. But the Facter code still exists in `lib/facter/gitlab_systemd.rb`, so that is still getting executed on client systems. I think there is still a reference in `spec/classes/init_spec.rb` as well.

Is the right thing to do here just remove the Facter file and the line in the init_spec.rb file?

**Comment by LongLiveCHIEF** [comment]
> Is the right thing to do here just remove the Facter file and the line in the init_spec.rb file?

Yes, most likely. I will take a closer look in the morning and provide an update.

**Comment by jkroepke** [comment]
@LongLiveCHIEF You merged already the PR that removed this fact.

https://github.com/voxpupuli/puppet-gitlab/pull/119/files#diff-648e4ce8fd98085b9aa4a0944a8105d7
