### ISSUE TITLE
Migrate Puppet Module to Voxpupuli

### ISSUE THREAD

**Issue by tobru** [voxpupuli/puppet-gitlab#171]
We decided to move the Puppet module to Voxpupuli. This will happen over the next days.

**Comment by law** [comment]
Is this still ongoing?

**Comment by tobru** [comment]
Yes it is, still missing a proper release on forge. See also https://github.com/voxpupuli/plumbing/issues/160

**Comment by mjburling** [comment]
I think this can be closed up now with the closure of voxpupuli/plumbing#160

**Comment by tobru** [comment]
Yes, this is finally done!
