### ISSUE TITLE
Support for letsencrypt options results in failures on Puppet >=3.7.0 <4.0.0

### ISSUE THREAD

**Issue by christopherhatton** [voxpupuli/puppet-gitlab#202]
With the use of Optional data type [gitlab/manifests/init.pp:381] results in failure on older Puppet 3 systems.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
- Distribution: CentOS Linux release 7.4.1708 (Core) 
- Module version: e9d8d2801428e9b5a9e1c0f44dedf63b7f89fb65

## How to reproduce (e.g Puppet code you use)

Applying the gitlab puppet module on a Puppet 3 machine

## What are you seeing

Since the introduction of the letsencrypt parameters the gitlab module we see the following message:

```Error: Syntax error at 'Optional'; expected ')' at /vagrant/puppet-control/modules/gitlab/manifests/init.pp:381 on node server1
Error: Syntax error at 'Optional'; expected ')' at /vagrant/puppet-control/modules/gitlab/manifests/init.pp:381 on node server1
```

I have added additional code to my Gitlab profile but this did not resolve the error:

```
 letsencrypt          => {
              enable => true,
              contact_emails => ['test@example.com']
            },
```
On further investigation I noticed that Puppet 3.x does not support the Optional data type.

## What behaviour did you expect instead

Support for older Puppet 3 systems

## Any additional information you'd like to impart

We have been using old vshn/gitlab: 1.9.1 and trying to switch to puppet-gitlab, for the support of gitlab runner new package name (166) and the issue recently identified with GPG package (196).

**Comment by juniorsysadmin** [comment]
@christopherhatton We don't support endeavour to Puppet 3.
See: https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/
