### ISSUE TITLE
YUM GPG keys are invalid

### ISSUE THREAD

**Issue by ayohrling** [voxpupuli/puppet-gitlab#203]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.6
- Ruby: 2.1.9
- Distribution: EL7
- Module version: 1.16.1

## How to reproduce (e.g Puppet code you use)
`include 'gitlab`

## What are you seeing
The yum repository has invalid GPG key reference for the new packages. Package fails to install for CE/.

## What behaviour did you expect instead
Install package with valid GPG keys

## Output log
Error: Execution of '/bin/yum -d 0 -e 0 -y install gitlab-ce' returned 1: warning: /var/cache/yum/x86_64/7/gi
tlab_official_ce/packages/gitlab-ce-10.5.3-ce.0.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f27eab47
: NOKEY
Public key for gitlab-ce-10.5.3-ce.0.el7.x86_64.rpm is not installed
The GPG keys listed for the "Official repository for Gitlab" repository are already installed but they are no
t correct for this package.
Check that the correct key URLs are configured for this repository.
 Failing package is: gitlab-ce-10.5.3-ce.0.el7.x86_64
 GPG Keys are configured as: https://packages.gitlab.com/gpg.key
Error: /Stage[main]/Gitlab::Install/Package[gitlab-ce]/ensure: change from purged to present failed: Executio
n of '/bin/yum -d 0 -e 0 -y install gitlab-ce' returned 1: warning: /var/cache/yum/x86_64/7/gitlab_official_c
e/packages/gitlab-ce-10.5.3-ce.0.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID f27eab47: NOKEY
Public key for gitlab-ce-10.5.3-ce.0.el7.x86_64.rpm is not installed

## Any additional information you'd like to impart
The new GPG key locations are:
gpgkey=https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
       https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg

**Comment by LongLiveCHIEF** [comment]
looks like we should be able to just point to the default gpg key at: https://packages.gitlab.com/gpg.key

**Comment by LongLiveCHIEF** [comment]
This was fixed in https://github.com/voxpupuli/puppet-gitlab/issues/196, and will be included in the next release.

I'm working on prepping that release now, planning on getting it into the forge in the next 3-4 days.
