### ISSUE TITLE
$web_server documentation differs from code

### ISSUE THREAD

**Issue by NiklausHofer** [voxpupuli/puppet-gitlab#217]
https://github.com/voxpupuli/puppet-gitlab/blob/f2ef16b98d2c892e931061595e280280e9b9c432/manifests/init.pp#L306-L308

https://github.com/voxpupuli/puppet-gitlab/blob/f2ef16b98d2c892e931061595e280280e9b9c432/manifests/init.pp#L431

`web_server` used to be of type hash, but now it is of type String. However, according to the documentation, it still is of type hash. So either the code or the documentation should be updated. I assume, that is is actually a bug in the code that appeared in commit 3fa7b17234c765e15c04b5f13aaf46b16710e27e

Same is also true for the `user` parameter.

**Comment by benaryorg** [comment]
Especially since they've been validated as `Hash`es before anyway:

https://github.com/voxpupuli/puppet-gitlab/blob/c00e24ebc0b0b8be31d0d37a303aa6d1b2747acd/manifests/init.pp#L494-L495
