### ISSUE TITLE
Manage letsencrypt options

### ISSUE THREAD

**Issue by guikcd** [voxpupuli/puppet-gitlab#224]
This is a feature request.

GitLab will enable Let's Encrypt by default if https is enabled from version `10.7`.
However, if there is an off-loading device in front on GitLab for TLS, the trafic maybe in http (other use case are: the GitLab Server can't be contacted without a load-balancer, you have another mecanism to handle certs, etc...).

Anyway, it would be great if options under 
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L1525-1538 will be integrated in this module.

Source: https://docs.gitlab.com/omnibus/settings/ssl.html#disabling-auto-configuration

**Comment by LongLiveCHIEF** [comment]
This was released in our [v2.0.0](https://github.com/voxpupuli/puppet-gitlab/releases/tag/v2.0.0) (about 2 weeks ago). Make sure you're using the latest version and you should be good to go!
