### ISSUE TITLE
New minor release required.

### ISSUE THREAD

**Issue by pazmarianoj** [voxpupuli/puppet-gitlab#225]
Based on the fact that tag 2.0.0 is bugged and doesn't successfully finish a clean run, and based on the fact that the issues in 2.0.0 were resolved and merged into master, I would like to have a 2.0.1 tag available for my production environments. 
I can't tag as master cause any bug accidentally merged into master will break my ecosystem.

Sure I'm open to be illuminated about the reasons for NOT doing a new release.
Thank you in advance.

**Comment by LongLiveCHIEF** [comment]
I'm not opposed to doing a release, but I _would_ like to know what issues you ran into so we can be sure the new release fixes them.

Can you be specific or link to relevant issues?

**Comment by LongLiveCHIEF** [comment]
Disregard my previous comments, I think you're referring to #223. 

Yes, I will prepare a new release in a few hours.

**Comment by LongLiveCHIEF** [comment]
Forgive me for asking the dumb question, I'm just trying to understand the various ways users utilize this module. In that context, I'm wondering why you haven't just changed your data source so it passes an actual boolean instead of a string?

**Comment by LongLiveCHIEF** [comment]
Darn, I forgot to put out a new release last night. I did however go back and think about this issue a bit harder, and I got to thinking about something. What happens if someone passes the values: `'true', 'false', 'TRUE', 'FALSE'`?

**Comment by pazmarianoj** [comment]
Any bool value that is passed in quotes to gitlab.rb has no effect, as far as I got from Gitlab EE Support people.

**Comment by LongLiveCHIEF** [comment]
For example, your hiera data should look like this:

```
gitlab::postgresql:
  enable: false
```

It _**should not**_ look like this:

```
gitlab::postgresql:
  enable: 'false'
```
