### ISSUE TITLE
Add support for zero-downtime updates

### ISSUE THREAD

**Issue by LongLiveCHIEF** [voxpupuli/puppet-gitlab#239]
Whenever a node is utilized as a deploy node, the `gitlab-ctl reconfigure` command should be run with an env of `SKIP_POST_DEPLOYMENT_MIGRATIONS=true`.  This shouldn't be a permanent env variable, for the node, so it makes sense to add a conditional to the `Exec['gitlab_reconfigure` that sets the `env =>` attribute whenever a node is identified by a `deploy_node` `boolean` variable for the module.

Additionally, the `Service['gitlab-runsvdir']` service is not designed to be restarted, and thus should not subscribe to config/package changes unless the implementor explicitly has a reason to do so.  `gitlab-runsvdir` is a supervisor for the bundle of gitlab services on the host, and `gitlab-ctl reconfigure` refreshes these services depending on the configs that changed.

If puppet sends a refresh signal to the service, it will cause gitlab services to shut down, and make it impossible to do zero downtime updates.

Zero Downtime Updates Doc: https://docs.gitlab.com/omnibus/update/README.html#zero-downtime-updates`

**Comment by baurmatt** [comment]
If you run Gitlab in a single server setup, you do not have a "deploy node" but you might need `SKIP_POST_DEPLOYMENT_MIGRATIONS` as well :)

**Comment by LongLiveCHIEF** [comment]
Yeah, that's why I worded it the way I did (not mentioning HA specifically). It's labeled with the HA Support Milestone merely because we can't really claim this module supports HA fully until this feature works.
