### ISSUE TITLE
manage_package_repo is gone and replacement is broken

### ISSUE THREAD

**Issue by KlavsKlavsen** [voxpupuli/puppet-gitlab#250]
When you removed manage_package_repo - a doc was added https://github.com/voxpupuli/puppet-gitlab/commit/517469bd45e4a9ef61884550302b1080e53e2540#diff-04c6e90faac2675aa89e2176d2eec7d8R188 - stating how to use the new.
It does however NOT work.
I made it work by adding:
  Optional[String]               $package_name                  = undef,
  Boolean                        $manage_omnibus_repository     = true,
to gitlab class - and make package::install - default to using $gitlab::package_name and obmibus_.. class - to using $gitlab::manage_ominibus_repository

Otherwise - one cannot use gitlab - and have repos handled by other modules.

**Comment by LongLiveCHIEF** [comment]
What version of this package are you using?

This has not yet been released, and as such is unstable. I don't recommend using `master` for your installation.  Use the latest stable release by viewing the [releases](https://github.com/voxpupuli/puppet-gitlab/releases) page, and use the docs in the `README.md` for the latest release.

**Comment by KlavsKlavsen** [comment]
I know.. I just checked out master and saw it was broken (for how I use it atleast :) I have kept my production gitlab version at an older release for now :)

**Comment by LongLiveCHIEF** [comment]
I'm going to be adding some more tests against the new functionality added before I release to make sure any issues are addressed. It _will_ be a breaking change though, so keep an eye out for things that will be different.

**Comment by LongLiveCHIEF** [comment]
@KlavsKlavsen I'm working through what tests I need to add to this, but I need some help with the usage case you're trying to explain.

The module is _designed_ to fail when you set `manage_upstream_edition => 'disabled'` and don't set `package_name` for `gitlab::install`.

What I'm trying to do is reduce the footprint of the docs in `manifests/init.pp` by factoring out things that are rarely used, or aren't directly related to the omnibus package, into the classes that configure them.

I _can_ go back to the scoped method you describe, but I'd like to see if this new way can work first. I'm going to be doing a series/book on puppet development patterns in Puppet 5+, and this is one of the patterns I'm exploring.

So to be clear, I'm not saying you're wrong about anything... I think there probably _is_ something I missed, I just need you to take another stab at explaining it.

Can you tell me what exactly you mean by: 

> Otherwise - one cannot use gitlab - and have repos handled by other modules.

Can you give me an example use case so I can add that as a test and scenario for a fix?

**Comment by KlavsKlavsen** [comment]
an example use case would be to add a gitlab-ce repo (from other class) pointing to local mirror - and have NO internet connection. Thats our issue.

**Comment by LongLiveCHIEF** [comment]
I think what you're saying, is that when you have some puppet code almost exactly like the code below, it fails. Right? If so can you provide me with the error you're seeing, along with any differences in your params for the `gitlab` and `gitlab::install` configurations?

```puppet
class my_gitlab_profile {
  class { 'gitlab':
    manage_upstream_edition => 'disabled'
  }
  class {'gitlab::install':
    ensure => '10.7.6-ce.0.el7',
    package_name => 'gitlab-ce'
  }
  class {'gitlab::omnibus_package_repository':
    repository_configuration => {}
  }
```

**Comment by LongLiveCHIEF** [comment]
@KlavsKlavsen i've went ahead and changed the way these variables are scoped up from the `init` manifest like normal. When I went to add the new class tests, I was getting the failures too, using the scenario above.

As a result, this should start working again with the new technique once #254 is merged. (all params are now on `class {'gitlab':` as you suggested.

**Comment by KlavsKlavsen** [comment]
Perfect.. thank you very much.. I hope you could use the "early feedback" on the module :)

**Comment by LongLiveCHIEF** [comment]
Definitely appreciated so i could address this before it made it to an official release. Thank you!
