### ISSUE TITLE
Dependency error when gitlab::service::service_manage is set to false

### ISSUE THREAD

**Issue by LongLiveCHIEF** [voxpupuli/puppet-gitlab#284]
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Service[gitlab-runsvdir]' in parameter 'require' (file: /etc/puppetlabs/code/environments/production/external_modules/gitlab/manifests/service.pp, line: 58) on node gitlab.local
```

**Comment by DaveTCode** [comment]
I just ran into this and was about to raise an issue for it, is there a standard release cycle for the module or do you typically wait until there's enough things fixed a release has some significant value?

**Comment by LongLiveCHIEF** [comment]
Usually just as needed. I've been the primary maintainer for a while now, but I've moved to kubernetes based installations and haven't paid as much attention to this module as I should.

I thought this fix was already released though. What version are you running of the module and of gitlab-omnibus?

**Comment by DaveTCode** [comment]
I ran into it testing out updating from a 1.* release of the module to 3.0.2, that _says_ it was released in October and the PR claims to be merged in December so I was just made the assumption it wasn't part of that release

**Comment by DaveTCode** [comment]
Having now actually checked what gets pulled down from the forge I can confirm 3.0.2 doesn't include the changes in the PR referenced

**Comment by DaveTCode** [comment]
Given my updates above that this fix isn't in 3.0.2, can I convince you to create 3.0.3? Honestly no hurry here but a vague idea of timeline would be useful for me to know how long to park our upgrade.

**Comment by LongLiveCHIEF** [comment]
You already conviced me, I just had some hardware issues last weekend and wound up having to re-install all my OS's on my dev machine that was set up to do releases.

I should be able to get set back up for releases by Thursday. If any of the other @voxpupuli/collaborators with release capabilities sees this before then, please feel free to release. I've already performed all the labeling so changelog should generate properly for this release.

**Comment by DaveTCode** [comment]
Oh yuck. Sounds fun! Thanks though, no need to update me through this, I'm happy to monitor forge for the release when it does come out.

**Comment by LongLiveCHIEF** [comment]
I just realized... the reason I didn't immediately push a release for this was that we separated out the ci_runner into its own module.

This doesn't change the release timeline, but it means you'll want to look for `4.0.0` instead of `3.0.3`.

If anyone gets to it first, please make sure to bump major version.

**Comment by alexjfisher** [comment]
Next version is already scheduled to be 4.0.0 as dropping puppet 4 is considered a breaking change.
I'll mark https://github.com/voxpupuli/puppet-gitlab/pull/293 as breaking too.
