### ISSUE TITLE
typo in .github/issue template

### ISSUE THREAD

**Issue by slmagus** [voxpupuli/puppet-gitlab#296]
"What behaviour did you expect instead"

behavior should be spelled correctly.

**Comment by rkcpi** [comment]
It is.

**Comment by bastelfreak** [comment]
Hi @slmagus. This is British English and not the American dialect. The spelling is correct.

**Comment by slmagus** [comment]
Ha. I guess so. All I could tell was spell checker kept marking it up. Thanks.
