### ISSUE TITLE
Add parameter to modify the prometheus storage retention period

### ISSUE THREAD

**Issue by alexandrujieanu** [voxpupuli/puppet-gitlab#299]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.7
- Ruby: 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Distribution: Ubuntu 16.04.4 LTS
- Module version: v3.0.2

## How to reproduce (e.g Puppet code you use)
I installed Gitlab with default prometheus settings.

## What are you seeing
Prometheus consumes approx 300MB/day and fills up the filesystem.

By default, Gitlab's Prometheus stores data for 365 days: https://gitlab.com/gitlab-cookbooks/gitlab-prometheus/merge_requests/2/diffs

I added this code to `/etc/gitlab/gitlab.rb` and ran `gitlab-ctl reconfigure`.
```
prometheus["flags"]["storage.local.retention"] = "72h0m0s"
```

The Gitlab is reconfigured properly:

```
    - update content in file /opt/gitlab/sv/prometheus/run from 60f91b to f65798
    --- /opt/gitlab/sv/prometheus/run   2019-02-04 12:42:11.902190365 +0000
    +++ /opt/gitlab/sv/prometheus/.chef-run20190225-14196-1xmduki       2019-02-25 08:08:44.690196993 +0000
    @@ -5,5 +5,5 @@
     exec chpst -P -e /opt/gitlab/etc/prometheus/env \
       -U gitlab-prometheus:gitlab-prometheus \
       -u gitlab-prometheus:gitlab-prometheus \
    -  /opt/gitlab/embedded/bin/prometheus --web.listen-address=localhost:9090 --storage.tsdb.path=/var/opt/gitlab/prometheus/data --config.file=/var/opt/gitlab/prometheus/prometheus.yml
    +  /opt/gitlab/embedded/bin/prometheus --web.listen-address=localhost:9090 --storage.tsdb.path=/var/opt/gitlab/prometheus/data --config.file=/var/opt/gitlab/prometheus/prometheus.yml --storage.local.retention=72h0m0s
```
## What behaviour did you expect instead
I expected to find an option to configure the `storage.local.retention` in `manifests/init.pp`, along with these:

```
# [*prometheus*]
#   Default: undef
#   Hash of 'prometheus' config parameters.
#
# [*prometheus_monitoring_enable*]
#   Default: undef
#   Enable/disable prometheus support.
#
```

**Comment by LongLiveCHIEF** [comment]
the `prometheus` param in `manifests/init.pp` is a `Hash`, so it already supports this.

if you use hiera:

```yaml
prometheus:
  flags:
    storage.local.retention: '72h0m0s'
```

Or if you're passing via class params in a manifest:

```puppet
class {'gitlab':
  prometheus => {
    'flags' => {
      'storage.local.retention' => '72h0m0s'
    }
  }
}
```
