### ISSUE TITLE
Need to know how to set the root password via this module

### ISSUE THREAD

**Issue by trevor-vaughan** [voxpupuli/puppet-gitlab#301]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5+
- Ruby: 2.4.4+
- Distribution: EL
- Module version: 3.0.3

## Feature Request

This is a feature request to be able to set the GitLab root password prior to installation. If this is not done, then you cannot do the following security-relevant actions:

* Prevent unauthorized people from setting the root password via the initial configuration page
* Generate an API key immediately for automatic configuration

The easiest method for doing this is to set an environment variable prior to the initial configuration but the [relevant feature](https://tickets.puppetlabs.com/browse/PUP-1526) never made it into Puppet even though it was ready for inclusion.

Previously, this was relatively easy using the `vshn` version of the module but has become impossible with this version due to the ordering of the internal resources.

Help figuring this out is appreciated.

**Comment by trevor-vaughan** [comment]
Additional information: https://github.com/simp/pupmod-simp-simp_gitlab/blob/master/manifests/install.pp#L47-L77

**Comment by LongLiveCHIEF** [comment]
The `initial_root_password` is one of the sub-keys for `gitlab_rails` (see [README.md#usage](https://github.com/voxpupuli/puppet-gitlab#usage)). This module implements the major keys from the [gitlab-config-template](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L443) from the gitlab omnibus. 


```
class {'gitlab':
  gitlab_rails => {
    'initial_root_password' => 'whatever_your_password'
  }
}
```

Keep in mind, this is only the _initial_ password, and will not affect the password for the root user of an existing gitlab installation.  This is also not a secure method of setting that password, (probably obvious but making sure it is said for the record).

**Comment by LongLiveCHIEF** [comment]
Also, reading the information in your link, the current version of the module has a new ordering (and was completely rewritten) of resources that resolves the exec and reconfigure issues your notes talk about.

The new versions of the module lay down configuration files and directories before even installing the package and repositories, ensuring that any `initial_root_password` you set will be used during the omnibus's own `post-install` execution of the reconfigure command.

Also, the new version of the module does _not_ by default start/restart the service _or_ execute gitlab-ctl reconfigure... relegating that responsibility to the `post-install` scripts of omnibus. (see `init.pp#372-L373`) https://github.com/voxpupuli/puppet-gitlab/blob/master/manifests/init.pp#L372
