### ISSUE TITLE
access to repo

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/puppet-gitlab#321]
@bastelfreak @alexjfisher checking all the links for the vp site and found I can't access https://github.com/voxpupuli/puppet-gitlab/settings/collaboration

**Comment by LongLiveCHIEF** [comment]
Only group owners can access those settings.

**Comment by bastelfreak** [comment]
Correct. Only the PMC people have admin access to the org. Collaborators have normal write access.
