### ISSUE TITLE
nginx still not documented

### ISSUE THREAD

**Issue by tquid** [voxpupuli/puppet-gitlab#371]
Although there was an issue from 2016 and a merged pull request regarding nginx configuration documentation, that pull request leads to something about the version of apt being used. The documentation still reads as [fixme]. Can we get this documented?

**Comment by kenyon** [comment]
You mean something besides this? https://github.com/voxpupuli/puppet-gitlab#nginx-configuration

**Comment by tquid** [comment]
Yes, in addition to that. Note this part:

> Details on available configuration options are available at [Fixme][NGINX settings].

**Comment by kenyon** [comment]
> Yes, in addition to that. Note this part:
> 
> > Details on available configuration options are available at [Fixme][NGINX settings].

@tquid I see. If you are able to provide any enhancement to the documentation, we would gladly accept it! Thanks.
