### ISSUE TITLE
unable to specify listen_port and listen_https

### ISSUE THREAD

**Issue by rbos** [voxpupuli/puppet-gitlab#413]
Feature request (or correction, if I just can't find it):

I'm running Gitlab behind a reverse proxy, so I need to specify:

nginx['listen_port'] = 80
nginx['listen_https'] = false

but there doesn't seem to be any way to do that in the Puppet module. Am I just missing something?

**Comment by smortex** [comment]
If you already have a proxy, no need to run nginx bundled with GitLab.  You can do something like this:

```
  class { 'gitlab':    
    external_url            => "https://${hostname}",    
    # ...
    nginx                   => {
      enable => false,
    },
    gitlab_workhorse        => {
      enable         => true,
      listen_network => 'tcp',
      listen_addr    => '127.0.0.1:8181',
    },
  }    
```

**Comment by rbos** [comment]
The reverse proxy isn't on the same machine - it's a load-balancer that handles traffic on a virtual IP with an attached SSL certificate. Does that matter?

Would I then configure gitlab_workhorse to listen on the machine's public interface on port 80?

**Comment by smortex** [comment]
The parameter of the `gitlab` module is `nginx` and is a hash.  So if using Hiera, this should be something like:

```yaml
gitlab::nginx:
  listen_port: 80
  listen_https: false
```

**Comment by rbos** [comment]
That does it; thanks.
