### ISSUE TITLE
gitlab_sshd support in the omnibus config

### ISSUE THREAD

**Issue by mallorn** [voxpupuli/puppet-gitlab#417]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.25
- Ruby: 2.7.8p225
- Distribution: Rocky 8.8
- Module version: 8.1.0

Hi,

We currently cannot configure the [gitlab_sshd part of the omnibus config](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L1201).

Sample code:

```
      gitlab_sshd => {
         enable => true,
         listen_address => 'git.example.com:2222',
      },
```

Error seen in Puppet:

`Class[Gitlab]: has no parameter named 'gitlab_sshd'`

The documentation states

`Please note, managing the sshd service and openssh is outside the scope of this module.`

Does this fall under that umbrella?  Is there any other way to put these options into the config file?  If we add them manually or via other puppet code they are overwritten.

**Comment by smortex** [comment]
This note in the documentation was introduced in 6dcb57ac671c7a7a5bf225bca49616dba7036aba (6 years ago) and predate the feature you are talking about which was introduced in https://gitlab.com/gitlab-org/omnibus-gitlab/-/commit/833c4489ace2a24ccdf21e53026f862877b60709 (5 months ago).

It seems fine to add support for this new configuration section if you have a need for it.  Maybe at that occasion rewording the note in the readme to make it less confusing would be great.
