### ISSUE TITLE
puppetlabs-stdlib

### ISSUE THREAD

**Issue by sandwitch** [voxpupuli/puppet-gitlab#424]
Is it possible to bump the puppetlabs-stdlib version to 9.4.1? Should i create a pull request?

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by kenyon** [comment]
Yes, create a pull request.

**Comment by sandwitch** [comment]
fixed in 8.1.1-rc0
