### ISSUE TITLE
Gitlab 18

### ISSUE THREAD

**Issue by rogermartensson** [voxpupuli/puppet-gitlab#451]
Gitlab 18 and forward are planning to make some big changes. Especially around databases.

Do you see anything that needs to be updated in the module for the next big releases of Gitlab?

**Comment by yakatz** [comment]
This module only uses the omnibus packages, so we will need to see what changes will need to be made to the `gitlab.rb.erb` template and corresponding changes to the configuration. Besides that, there shouldn't be any major changes required to the theory of operation of the module.

**Comment by rogermartensson** [comment]
Thank you for your answer and your work. I guess we will wait and see. Version 18 is still some way off before releasing.
